### PR TITLE
opentracing version upgrade

### PR DESCRIPTION
**Pull request by NarimanAB**

### CODE REVIEW

**Comment by nelsonjunior** [comment]
Hello I was having problems and applying the corrections of this pull request solved the problem. Could you add the version?

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
For some reason, I didn't have this on my radar. PR merged, and a new version is coming soon (hopefully).

**Comment by nelsonjunior** [comment]
You have already tried to use this lib in the Websphere Server Application. I tried more is giving a websphere error by: java.lang.NoSuchMethodError: io / opentracing / ScopeManager.active () Lio / opentracing / Scope

**Comment by jpkrohling** [comment]
No, not on Websphere. When I first developed this, I did try this on Wildfly: https://dzone.com/articles/opentracing-ejb-instrumentation-on-wildfly-swarm

**Pull request merged**
